#!/usr/bin/env python3
"""Generate or refresh the section index at the top of every large library file.

Files in modes/, docs/, and practice/ routinely run 2,000-5,000 lines with 80-100
sections. Without an index at the top, the only way to find a section is to read the
whole file, which is exactly what a skill's bundled resources are supposed to avoid.

The index lets a reader load ~100 lines, find the section it needs, and jump straight
there. Re-run this script after adding or renaming sections so the index never drifts
out of sync with the file it describes.

Usage:
    python scripts/generate_tocs.py            # rewrite indexes in place
    python scripts/generate_tocs.py --check    # exit 1 if any index is stale
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
TARGET_DIRS = ("modes", "docs", "practice")

# Only worth indexing when there is enough material to get lost in.
MIN_SECTIONS = 8

BEGIN = "<!-- BEGIN SECTION INDEX (generated by scripts/generate_tocs.py) -->"
END = "<!-- END SECTION INDEX -->"

FENCE = re.compile(r"^(```|~~~)")
H2 = re.compile(r"^##\s+(?!#)(.+?)\s*$")


def slugify(heading: str) -> str:
    """Match GitHub's anchor generation so the links actually resolve."""
    text = heading.strip().lower()
    text = re.sub(r"[`*_~]", "", text)          # strip inline markdown
    text = re.sub(r"[^\w\s-]", "", text)        # drop punctuation
    text = re.sub(r"\s+", "-", text.strip())
    return text


def collect_headings(lines: list[str]) -> list[str]:
    """Return H2 headings, ignoring anything inside a fenced code block."""
    headings: list[str] = []
    in_fence = False
    for line in lines:
        if FENCE.match(line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        match = H2.match(line)
        if match:
            headings.append(match.group(1))
    return headings


def build_index(headings: list[str]) -> str:
    entries = "\n".join(f"- [{h}](#{slugify(h)})" for h in headings)
    return (
        f"{BEGIN}\n"
        f"## Section Index\n\n"
        f"{len(headings)} sections. Jump to the one you need rather than reading "
        f"this file end to end.\n\n"
        f"{entries}\n"
        f"{END}"
    )


def strip_existing(text: str) -> str:
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n*", re.DOTALL)
    return pattern.sub("", text)


def first_section_offset(lines: list[str]) -> int:
    """Insert point: just before the first real H2 heading."""
    in_fence = False
    for i, line in enumerate(lines):
        if FENCE.match(line):
            in_fence = not in_fence
            continue
        if not in_fence and H2.match(line):
            return i
    return len(lines)


def process(path: Path, check_only: bool) -> bool:
    """Return True if the file was (or would be) changed."""
    original = path.read_text(encoding="utf-8")
    body = strip_existing(original)
    lines = body.splitlines()

    headings = collect_headings(lines)
    if len(headings) < MIN_SECTIONS:
        # Small file: an index would be noise. Ensure any stale one is removed.
        return _write(path, original, body, check_only)

    insert_at = first_section_offset(lines)
    index = build_index(headings)
    updated = "\n".join(lines[:insert_at] + [index, ""] + lines[insert_at:])
    if not updated.endswith("\n"):
        updated += "\n"
    return _write(path, original, updated, check_only)


def _write(path: Path, original: str, updated: str, check_only: bool) -> bool:
    if updated == original:
        return False
    if not check_only:
        path.write_text(updated, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="report stale indexes without rewriting; exit 1 if any are found",
    )
    args = parser.parse_args()

    changed: list[Path] = []
    for directory in TARGET_DIRS:
        for path in sorted((REPO / directory).rglob("*.md")):
            if process(path, args.check):
                changed.append(path.relative_to(REPO))

    if args.check:
        if changed:
            print(f"{len(changed)} file(s) have a stale or missing section index:")
            for path in changed:
                print(f"  {path}")
            print("\nRun: python scripts/generate_tocs.py")
            return 1
        print("All section indexes are up to date.")
        return 0

    print(f"Updated section index in {len(changed)} file(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
